### ISSUE TITLE
Run certain queries on certain databases 

### ISSUE THREAD

**Issue by dan-aksenov** [weaponry/pgscv#11]
**Is your feature request related to a problem? Please describe.**
We wont to collect business metrics from databases.
It requires running certain queries on specific databases only 

**Describe the solution you'd like**
I think solution should look like:
```
collectors:
  bsuness_metric1:
    filters:
      database:
        include: "business_db1"
    subsystems:
      business_query11:
        query: "select foo from bar"
        ...
   bsuness_metric2:
    filters:
      database:
        include: "business_db2"
    subsystems:
      business_query12:
        query: "select baz from ban"
        ...
```
**Describe alternatives you've considered**
We tried [postgres_exporer](https://github.com/prometheus-community/postgres_exporter/issues/443), but it doesn't have such feature ether.

**Additional context**
None
